apiVersion: v1
kind: Service 
metadata:
  name: {{ .Release.Name }}-service
  app: {{ .Release.Name }}
spec:
  selector:
    app-pod: {{ .Release.Name }}-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: app-port